import yake
from rake_nltk import Rake
stopwords = list(map(lambda x:x.strip(),open('stopwords.txt','r').readlines()))
text = str(input("Input Text for which you want to generate keywords \n"))

#yake Algorithm for keyword Extraction
custom_kwextractor = yake.KeywordExtractor(lan="en", n=1, dedupLim=0.8, windowsSize=2, top=5)
yake_keywords = list(map(lambda x : x[1],custom_kwextractor.extract_keywords(text)))
print("Keyword generated by Algorithm # 1 (yake) are : ", yake_keywords)

#RAKE Algorithm for keyword Extraction
r = Rake(min_length=1, max_length=3,stopwords=stopwords) # Uses stopwords for english, and all puntuation characters.
r.extract_keywords_from_text(text)
rake_keywords = r.get_ranked_phrases() # To get keyword phrases ranked highest to lowest.
print("Phrases generated by Algorithm # 2 (RAKE) are : ", rake_keywords)